=== edewata/penrose-server/common/src/java/org/safehaus/penrose/module/modules.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT modules (module*, module-mapping*)>

<!ELEMENT module (description?, module-class, parameter*)>
<!ATTLIST module name CDATA #IMPLIED>
<!ATTLIST module enabled CDATA #IMPLIED>
<!ELEMENT module-class (#PCDATA)>

<!ELEMENT module-mapping (module-name, base-dn, filter, scope)>
<!ELEMENT module-name (#PCDATA)>
<!ELEMENT base-dn (#PCDATA)>
<!ELEMENT filter (#PCDATA)>
<!ELEMENT scope (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== edewata/penrose-server/samples/federation/templates/ldap/DIR-INF/modules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>

  <module name="IdentityLinking" enabled="true">
    <module-class>org.safehaus.penrose.federation.module.IdentityLinkingModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>LDAP</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>federation.LDAP</param-value>
    </parameter>
    <parameter>
      <param-name>sourceKey</param-name>
      <param-value>dn</param-value>
    </parameter>
    <parameter>
    <param-name>targetAttribute</param-name>
      <param-value>seeAlso</param-value>
    </parameter>
    <parameter>
      <param-name>mapping</param-name>
      <param-value>import_users</param-value>
    </parameter>
    <parameter>
      <param-name>mappingPrefix</param-name>
      <param-value>l</param-value>
    </parameter>
  </module>

</modules>

=== edewata/penrose-server/samples/samba_ipa/DIR-INF/modules-monitor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>

  <module name="SambaChangeLogMonitorModule">
    <module-class>org.safehaus.penrose.ipa.module.ChangeLogMonitorModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>samba</param-value>
    </parameter>
    <parameter>
      <param-name>sourceUsers</param-name>
      <param-value>sambaUsers</param-value>
    </parameter>
    <parameter>
      <param-name>sourceGroups</param-name>
      <param-value>sambaGroups</param-value>
    </parameter>
    <parameter>
      <param-name>sourceHosts</param-name>
      <param-value>sambaHosts</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>ipa</param-value>
    </parameter>
    <parameter>
      <param-name>targetUsers</param-name>
      <param-value>ipaUsers</param-value>
    </parameter>
    <parameter>
      <param-name>targetGroups</param-name>
      <param-value>ipaGroups</param-value>
    </parameter>
    <parameter>
      <param-name>targetHosts</param-name>
      <param-value>ipaHosts</param-value>
    </parameter>
    <parameter>
      <param-name>changelog</param-name>
      <param-value>samba_changelog</param-value>
    </parameter>
    <parameter>
      <param-name>tracker</param-name>
      <param-value>samba_tracker</param-value>
    </parameter>
    <parameter>
      <param-name>userSyncModule</param-name>
      <param-value>SambaIPAUserModule</param-value>
    </parameter>
    <parameter>
      <param-name>groupSyncModule</param-name>
      <param-value>SambaIPAGroupModule</param-value>
    </parameter>
  </module>

</modules>

=== edewata/penrose-server/samples/federation/DIR-INF/modules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>
  
  <module name="Federation">
    <module-class>org.safehaus.penrose.federation.module.FederationModule</module-class>
    <parameter>
      <param-name>config</param-name>
      <param-value>federation.xml</param-value>
    </parameter>
    <parameter>
      <param-name>repositoryTypes</param-name>
      <param-value>LDAP,NIS</param-value>
    </parameter>
    <parameter>
      <param-name>conflictDetections</param-name>
      <param-value>Users,Groups</param-value>
    </parameter>
  </module>

  <module name="LDAP">
    <module-class>org.safehaus.penrose.federation.module.LDAPRepositoryModule</module-class>
  </module>

  <module name="NIS">
    <module-class>org.safehaus.penrose.federation.module.NISRepositoryModule</module-class>
  </module>

  <module name="Users">
    <module-class>org.safehaus.penrose.federation.module.ConflictDetectionModule</module-class>
    <parameter>
      <param-name>objectClass</param-name>
      <param-value>posixAccount</param-value>
    </parameter>
    <parameter>
      <param-name>attribute</param-name>
      <param-value>uidNumber</param-value>
    </parameter>
  </module>

  <module name="Groups">
    <module-class>org.safehaus.penrose.federation.module.ConflictDetectionModule</module-class>
    <parameter>
      <param-name>objectClass</param-name>
      <param-value>posixGroup</param-value>
    </parameter>
    <parameter>
      <param-name>attribute</param-name>
      <param-value>gidNumber</param-value>
    </parameter>
  </module>

</modules>
