=== edewata/penrose-server/common/src/java/org/safehaus/penrose/module/modules.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT modules (module*, module-mapping*)>

<!ELEMENT module (description?, module-class, parameter*)>
<!ATTLIST module name CDATA #IMPLIED>
<!ATTLIST module enabled CDATA #IMPLIED>
<!ELEMENT module-class (#PCDATA)>

<!ELEMENT module-mapping (module-name, base-dn, filter, scope)>
<!ELEMENT module-name (#PCDATA)>
<!ELEMENT base-dn (#PCDATA)>
<!ELEMENT filter (#PCDATA)>
<!ELEMENT scope (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== edewata/penrose-server/samples/samba_ipa/DIR-INF/modules-user.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>

  <module name="SambaIPAUserModule">
    <module-class>org.safehaus.penrose.samba.module.SambaIPAUserSyncModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>samba</param-value>
    </parameter>
    <parameter>
      <param-name>sourceUsers</param-name>
      <param-value>sambaUsers</param-value>
    </parameter>
    <parameter>
      <param-name>sourceKeyAttribute</param-name>
      <param-value>sAMAccountName</param-value>
    </parameter>
    <parameter>
      <param-name>sourceLinkAttribute</param-name>
      <param-value>nsUniqueId</param-value>
    </parameter>
    <parameter>
      <param-name>targetImportUserMapping</param-name>
      <param-value>IPAImportUser</param-value>
    </parameter>
    <parameter>
      <param-name>targetLinkUserMapping</param-name>
      <param-value>IPALinkUser</param-value>
    </parameter>
    <parameter>
      <param-name>sourceLinkUserMapping</param-name>
      <param-value>SambaLinkUser</param-value>
    </parameter>
    <parameter>
      <param-name>targetSyncUserMapping</param-name>
      <param-value>IPASyncUser</param-value>
    </parameter>
    <parameter>
      <param-name>targetUnlinkUserMapping</param-name>
      <param-value>IPAUnlinkUser</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>ipa</param-value>
    </parameter>
    <parameter>
      <param-name>targetUsers</param-name>
      <param-value>ipaUsers</param-value>
    </parameter>
    <parameter>
      <param-name>targetKeyAttribute</param-name>
      <param-value>uid</param-value>
    </parameter>
    <parameter>
      <param-name>targetLinkAttribute</param-name>
      <param-value>ntUniqueId</param-value>
    </parameter>
    <parameter>
      <param-name>ignoreDn.count</param-name>
      <param-value>1</param-value>
    </parameter>
    <parameter>
      <param-name>ignoreDn.1</param-name>
      <param-value>CN=Sync,CN=Users,DC=example,DC=com</param-value>
    </parameter>
  </module>

</modules>

=== edewata/penrose-server/samples/cache/DIR-INF/modules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>

  <module name="Cache">
    <module-class>org.safehaus.penrose.cache.module.CacheModule</module-class>
    <parameter>
      <param-name>querySize</param-name>
      <param-value>5</param-value>
    </parameter>
    <parameter>
      <param-name>resultSize</param-name>
      <param-value>5</param-value>
    </parameter>
    <parameter>
      <param-name>expiration</param-name>
      <param-value>3</param-value>
    </parameter>
  </module>

  <module-mapping>
    <module-name>Cache</module-name>
    <base-dn>dc=Cache,dc=Example,dc=com</base-dn>
  </module-mapping>

</modules>

=== edewata/penrose-server/samples/ipa_samba/DIR-INF/modules-user.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>

  <module name="IPASambaUserModule">
    <module-class>org.safehaus.penrose.ipa.module.IPASambaUserSyncModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>ipa</param-value>
    </parameter>
    <parameter>
      <param-name>sourceUsers</param-name>
      <param-value>ipa_users</param-value>
    </parameter>
    <parameter>
      <param-name>sourceKeyAttribute</param-name>
      <param-value>uid</param-value>
    </parameter>
    <parameter>
      <param-name>sourceLinkAttribute</param-name>
      <param-value>ntUniqueId</param-value>
    </parameter>
    <parameter>
      <param-name>targetImportUserMapping</param-name>
      <param-value>SambaImportUser</param-value>
    </parameter>
    <parameter>
      <param-name>sourceImportUserMapping</param-name>
      <param-value>IPAImportUser</param-value>
    </parameter>
    <parameter>
      <param-name>targetLinkUserMapping</param-name>
      <param-value>SambaLinkUser</param-value>
    </parameter>
    <parameter>
      <param-name>sourceLinkUserMapping</param-name>
      <param-value>IPALinkUser</param-value>
    </parameter>
    <parameter>
      <param-name>targetSyncUserMapping</param-name>
      <param-value>SambaSyncUser</param-value>
    </parameter>
    <parameter>
      <param-name>targetUnlinkUserMapping</param-name>
      <param-value>SambaUnlinkUser</param-value>
    </parameter>
    <parameter>
      <param-name>sourceUnlinkUserMapping</param-name>
      <param-value>IPAUnlinkUser</param-value>
    </parameter>
    <parameter>
      <param-name>targetAlias</param-name>
      <param-value>samba</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>sambaFE</param-value>
    </parameter>
    <parameter>
      <param-name>targetUsersFE</param-name>
      <param-value>sambaUsersFE</param-value>
    </parameter>
    <parameter>
      <param-name>targetUsersBE</param-name>
      <param-value>sambaUsersBE</param-value>
    </parameter>
    <parameter>
      <param-name>targetKeyAttribute</param-name>
      <param-value>sAMAccountName</param-value>
    </parameter>
    <parameter>
      <param-name>targetLinkAttribute</param-name>
      <param-value>nsUniqueId</param-value>
    </parameter>
  </module>

</modules>

=== edewata/penrose-server/samples/module/DIR-INF/modules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>

  <module name="DemoModule">
    <module-class>org.safehaus.penrose.example.module.DemoModule</module-class>
  </module>

  <module-mapping>
    <module-name>DemoModule</module-name>
    <base-dn>ou=Users,dc=Module,dc=Example,dc=com</base-dn>
    <filter>(objectClass=*)</filter>
    <scope>SUBTREE</scope>
  </module-mapping>

</modules>

=== edewata/penrose-server/samples/ipa_samba/DIR-INF/modules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>

  <module name="IPASambaUserModule">
    <module-class>org.safehaus.penrose.ipa.module.IPASambaUserSyncModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>ipa</param-value>
    </parameter>
    <parameter>
      <param-name>sourceUsers</param-name>
      <param-value>ipa_users</param-value>
    </parameter>
    <parameter>
      <param-name>sourceKeyAttribute</param-name>
      <param-value>uid</param-value>
    </parameter>
    <parameter>
      <param-name>sourceLinkAttribute</param-name>
      <param-value>ntUniqueId</param-value>
    </parameter>
    <parameter>
      <param-name>targetImportUserMapping</param-name>
      <param-value>SambaImportUser</param-value>
    </parameter>
    <parameter>
      <param-name>sourceImportUserMapping</param-name>
      <param-value>IPAImportUser</param-value>
    </parameter>
    <parameter>
      <param-name>targetLinkUserMapping</param-name>
      <param-value>SambaLinkUser</param-value>
    </parameter>
    <parameter>
      <param-name>sourceLinkUserMapping</param-name>
      <param-value>IPALinkUser</param-value>
    </parameter>
    <parameter>
      <param-name>targetSyncUserMapping</param-name>
      <param-value>SambaSyncUser</param-value>
    </parameter>
    <parameter>
      <param-name>targetUnlinkUserMapping</param-name>
      <param-value>SambaUnlinkUser</param-value>
    </parameter>
    <parameter>
      <param-name>sourceUnlinkUserMapping</param-name>
      <param-value>IPAUnlinkUser</param-value>
    </parameter>
    <parameter>
      <param-name>targetAlias</param-name>
      <param-value>samba</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>sambaFE</param-value>
    </parameter>
    <parameter>
      <param-name>targetUsersFE</param-name>
      <param-value>sambaUsersFE</param-value>
    </parameter>
    <parameter>
      <param-name>targetUsersBE</param-name>
      <param-value>sambaUsersBE</param-value>
    </parameter>
    <parameter>
      <param-name>targetKeyAttribute</param-name>
      <param-value>sAMAccountName</param-value>
    </parameter>
    <parameter>
      <param-name>targetLinkAttribute</param-name>
      <param-value>nsUniqueId</param-value>
    </parameter>
  </module>

  <module name="IPASambaGroupModule">
    <module-class>org.safehaus.penrose.ipa.module.GroupSyncModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>ipa</param-value>
    </parameter>
    <parameter>
      <param-name>sourceUsers</param-name>
      <param-value>ipa_users</param-value>
    </parameter>
    <parameter>
      <param-name>sourceGroups</param-name>
      <param-value>ipa_groups</param-value>
    </parameter>
    <parameter>
      <param-name>sourceKeyAttribute</param-name>
      <param-value>cn</param-value>
    </parameter>
    <parameter>
      <param-name>sourceLinkAttribute</param-name>
      <param-value>ntUniqueId</param-value>
    </parameter>
    <parameter>
      <param-name>importSourceGroupMapping</param-name>
      <param-value>ImportIPAGroup</param-value>
    </parameter>
    <parameter>
      <param-name>importTargetGroupMapping</param-name>
      <param-value>ImportSambaGroup</param-value>
    </parameter>
    <parameter>
      <param-name>linkSourceGroupMapping</param-name>
      <param-value>LinkIPAGroup</param-value>
    </parameter>
    <parameter>
      <param-name>linkTargetGroupMapping</param-name>
      <param-value>LinkSambaGroup</param-value>
    </parameter>
    <parameter>
      <param-name>syncSourceGroupMapping</param-name>
      <param-value>SyncIPAGroup</param-value>
    </parameter>
    <parameter>
      <param-name>syncTargetGroupMapping</param-name>
      <param-value>SyncSambaGroup</param-value>
    </parameter>
    <parameter>
      <param-name>unlinkSourceGroupMapping</param-name>
      <param-value>UnlinkIPAGroup</param-value>
    </parameter>
    <parameter>
      <param-name>unlinkTargetGroupMapping</param-name>
      <param-value>UnlinkSambaGroup</param-value>
    </parameter>
    <parameter>
      <param-name>targetAlias</param-name>
      <param-value>samba</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>sambaFE</param-value>
    </parameter>
    <parameter>
      <param-name>targetGroups</param-name>
      <param-value>sambaGroupsBE</param-value>
    </parameter>
    <parameter>
      <param-name>targetKeyAttribute</param-name>
      <param-value>sAMAccountName</param-value>
    </parameter>
    <parameter>
      <param-name>targetLinkAttribute</param-name>
      <param-value>nsUniqueId</param-value>
    </parameter>
    <parameter>
      <param-name>userSyncModule</param-name>
      <param-value>IPASambaUserModule</param-value>
    </parameter>
  </module>

  <module name="ChangeLogMonitorModule">
    <module-class>org.safehaus.penrose.ipa.module.ChangeLogMonitorModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>ipa</param-value>
    </parameter>
    <parameter>
      <param-name>sourceUsers</param-name>
      <param-value>ipa_users</param-value>
    </parameter>
    <parameter>
      <param-name>sourceGroups</param-name>
      <param-value>ipa_groups</param-value>
    </parameter>
    <parameter>
      <param-name>sourceHosts</param-name>
      <param-value>ipa_hosts</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>sambaBE</param-value>
    </parameter>
    <parameter>
      <param-name>targetWrite</param-name>
      <param-value>sambaFE</param-value>
    </parameter>
    <parameter>
      <param-name>targetUsers</param-name>
      <param-value>sambaUsersBE</param-value>
    </parameter>
    <parameter>
      <param-name>targetGroups</param-name>
      <param-value>sambaGroupsBE</param-value>
    </parameter>
    <parameter>
      <param-name>targetHosts</param-name>
      <param-value>sambaHosts</param-value>
    </parameter>
    <parameter>
      <param-name>changelog</param-name>
      <param-value>ipa_changelog</param-value>
    </parameter>
    <parameter>
      <param-name>tracker</param-name>
      <param-value>ipa_tracker</param-value>
    </parameter>
    <parameter>
      <param-name>userSyncModule</param-name>
      <param-value>IPASambaUserModule</param-value>
    </parameter>
    <parameter>
      <param-name>groupSyncModule</param-name>
      <param-value>IPASambaGroupModule</param-value>
    </parameter>
  </module>

</modules>

=== edewata/penrose-server/samples/operational/DIR-INF/modules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>

  <module name="OperationalAttributeModule">
    <module-class>org.safehaus.penrose.operationalAttribute.OperationalAttributeModule</module-class>
  </module>

  <module-mapping>
    <module-name>OperationalAttributeModule</module-name>
    <base-dn>dc=Operational Attribute,dc=Example,dc=com</base-dn>
    <filter>(objectClass=*)</filter>
    <scope>SUBTREE</scope>
  </module-mapping>

</modules>

=== edewata/penrose-server/samples/ad_sync/DIR-INF/modules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>

  <module name="users">
    <module-class>org.safehaus.penrose.ad.module.ADSyncModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>users</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>users_cache</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>interval</param-name>
      <param-value>10</param-value>
    </parameter>
  </module>

  <module name="groups">
    <module-class>org.safehaus.penrose.ad.module.ADSyncModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>groups</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>groups_cache</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>interval</param-name>
      <param-value>10</param-value>
    </parameter>
  </module>

</modules>

=== edewata/penrose-server/samples/jdbc_sync/DIR-INF/modules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>

  <module name="users">
    <module-class>org.safehaus.penrose.jdbc.module.JDBCSyncModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>users</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>users_cache</param-value>
    </parameter>
    <parameter>
      <param-name>changelog</param-name>
      <param-value>users_changelog</param-value>
    </parameter>
    <parameter>
      <param-name>tracker</param-name>
      <param-value>users_tracker</param-value>
    </parameter>
  </module>

  <module name="groups">
    <module-class>org.safehaus.penrose.jdbc.module.JDBCSyncModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>groups</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>groups_cache</param-value>
    </parameter>
    <parameter>
      <param-name>changelog</param-name>
      <param-value>groups_changelog</param-value>
    </parameter>
    <parameter>
      <param-name>tracker</param-name>
      <param-value>groups_tracker</param-value>
    </parameter>
  </module>

  <module name="usergroups">
    <module-class>org.safehaus.penrose.jdbc.module.JDBCSyncModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>usergroups</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>usergroups_cache</param-value>
    </parameter>
    <parameter>
      <param-name>changelog</param-name>
      <param-value>usergroups_changelog</param-value>
    </parameter>
    <parameter>
      <param-name>tracker</param-name>
      <param-value>usergroups_tracker</param-value>
    </parameter>
  </module>

</modules>
