=== edewata/penrose-server/common/src/java/org/safehaus/penrose/module/modules.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT modules (module*, module-mapping*)>

<!ELEMENT module (description?, module-class, parameter*)>
<!ATTLIST module name CDATA #IMPLIED>
<!ATTLIST module enabled CDATA #IMPLIED>
<!ELEMENT module-class (#PCDATA)>

<!ELEMENT module-mapping (module-name, base-dn, filter, scope)>
<!ELEMENT module-name (#PCDATA)>
<!ELEMENT base-dn (#PCDATA)>
<!ELEMENT filter (#PCDATA)>
<!ELEMENT scope (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== edewata/penrose-server/samples/ipa_samba/DIR-INF/modules-monitor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>

  <module name="ChangeLogMonitorModule">
    <module-class>org.safehaus.penrose.ipa.module.ChangeLogMonitorModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>ipa</param-value>
    </parameter>
    <parameter>
      <param-name>sourceUsers</param-name>
      <param-value>ipa_users</param-value>
    </parameter>
    <parameter>
      <param-name>sourceGroups</param-name>
      <param-value>ipa_groups</param-value>
    </parameter>
    <parameter>
      <param-name>sourceHosts</param-name>
      <param-value>ipa_hosts</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>sambaBE</param-value>
    </parameter>
    <parameter>
      <param-name>targetWrite</param-name>
      <param-value>sambaFE</param-value>
    </parameter>
    <parameter>
      <param-name>targetUsers</param-name>
      <param-value>sambaUsersBE</param-value>
    </parameter>
    <parameter>
      <param-name>targetGroups</param-name>
      <param-value>sambaGroupsBE</param-value>
    </parameter>
    <parameter>
      <param-name>targetHosts</param-name>
      <param-value>sambaHosts</param-value>
    </parameter>
    <parameter>
      <param-name>changelog</param-name>
      <param-value>ipa_changelog</param-value>
    </parameter>
    <parameter>
      <param-name>tracker</param-name>
      <param-value>ipa_tracker</param-value>
    </parameter>
    <parameter>
      <param-name>userSyncModule</param-name>
      <param-value>IPASambaUserModule</param-value>
    </parameter>
    <parameter>
      <param-name>groupSyncModule</param-name>
      <param-value>IPASambaGroupModule</param-value>
    </parameter>
  </module>

</modules>

=== edewata/penrose-server/samples/samba_ipa/DIR-INF/modules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>

  <module name="SambaIPAUserModule">
    <module-class>org.safehaus.penrose.samba.module.SambaIPAUserSyncModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>samba</param-value>
    </parameter>
    <parameter>
      <param-name>sourceUsers</param-name>
      <param-value>samba_users</param-value>
    </parameter>
    <parameter>
      <param-name>sourceKeyAttribute</param-name>
      <param-value>sAMAccountName</param-value>
    </parameter>
    <parameter>
      <param-name>sourceLinkAttribute</param-name>
      <param-value>nsUniqueId</param-value>
    </parameter>
    <parameter>
      <param-name>importSourceUserMapping</param-name>
      <param-value>ImportSambaUser</param-value>
    </parameter>
    <parameter>
      <param-name>linkTargetUserMapping</param-name>
      <param-value>LinkIPAUser</param-value>
    </parameter>
    <parameter>
      <param-name>linkSourceUserMapping</param-name>
      <param-value>LinkSambaUser</param-value>
    </parameter>
    <parameter>
      <param-name>syncSourceUserMapping</param-name>
      <param-value>SyncSambaUser</param-value>
    </parameter>
    <parameter>
      <param-name>unlinkTargetUserMapping</param-name>
      <param-value>UnlinkIPAUser</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>ipa</param-value>
    </parameter>
    <parameter>
      <param-name>targetUsers</param-name>
      <param-value>ipaUsers</param-value>
    </parameter>
    <parameter>
      <param-name>targetKeyAttribute</param-name>
      <param-value>uid</param-value>
    </parameter>
    <parameter>
      <param-name>targetLinkAttribute</param-name>
      <param-value>ntUniqueId</param-value>
    </parameter>
    <parameter>
      <param-name>ignoreDn.count</param-name>
      <param-value>1</param-value>
    </parameter>
    <parameter>
      <param-name>ignoreDn.1</param-name>
      <param-value>CN=Sync,CN=Users,DC=example,DC=com</param-value>
    </parameter>
  </module>

  <module name="SambaIPAGroupModule">
    <module-class>org.safehaus.penrose.ipa.module.GroupSyncModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>samba</param-value>
    </parameter>
    <parameter>
      <param-name>sourceUsers</param-name>
      <param-value>samba_users</param-value>
    </parameter>
    <parameter>
      <param-name>sourceGroups</param-name>
      <param-value>samba_groups</param-value>
    </parameter>
    <parameter>
      <param-name>sourceKeyAttribute</param-name>
      <param-value>sAMAccountName</param-value>
    </parameter>
    <parameter>
      <param-name>sourceLinkAttribute</param-name>
      <param-value>objectGUID</param-value>
    </parameter>
    <parameter>
      <param-name>importSourceGroupMapping</param-name>
      <param-value>ImportSambaGroup</param-value>
    </parameter>
    <parameter>
      <param-name>syncSourceGroupMapping</param-name>
      <param-value>SyncSambaGroup</param-value>
    </parameter>
    <parameter>
      <param-name>unlinkSourceGroupMapping</param-name>
      <param-value>UnlinkSambaGroup</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>ipa</param-value>
    </parameter>
    <parameter>
      <param-name>targetGroups</param-name>
      <param-value>ipa_groups</param-value>
    </parameter>
    <parameter>
      <param-name>targetKeyAttribute</param-name>
      <param-value>cn</param-value>
    </parameter>
    <parameter>
      <param-name>targetLinkAttribute</param-name>
      <param-value>objectGUID</param-value>
    </parameter>
    <parameter>
      <param-name>userSyncModule</param-name>
      <param-value>SambaIPAUserModule</param-value>
    </parameter>
  </module>

  <module name="SambaChangeLogMonitorModule">
    <module-class>org.safehaus.penrose.ipa.module.ChangeLogMonitorModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>samba</param-value>
    </parameter>
    <parameter>
      <param-name>sourceUsers</param-name>
      <param-value>samba_users</param-value>
    </parameter>
    <parameter>
      <param-name>sourceGroups</param-name>
      <param-value>samba_groups</param-value>
    </parameter>
    <parameter>
      <param-name>sourceHosts</param-name>
      <param-value>samba_hosts</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>ipa</param-value>
    </parameter>
    <parameter>
      <param-name>targetUsers</param-name>
      <param-value>ipa_users</param-value>
    </parameter>
    <parameter>
      <param-name>targetGroups</param-name>
      <param-value>ipa_groups</param-value>
    </parameter>
    <parameter>
      <param-name>targetHosts</param-name>
      <param-value>ipa_hosts</param-value>
    </parameter>
    <parameter>
      <param-name>changelog</param-name>
      <param-value>samba_changelog</param-value>
    </parameter>
    <parameter>
      <param-name>tracker</param-name>
      <param-value>samba_tracker</param-value>
    </parameter>
    <parameter>
      <param-name>userSyncModule</param-name>
      <param-value>SambaIPAUserModule</param-value>
    </parameter>
    <parameter>
      <param-name>groupSyncModule</param-name>
      <param-value>SambaIPAGroupModule</param-value>
    </parameter>
  </module>

</modules>

=== edewata/penrose-server/samples/samba/DIR-INF/modules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>

  <module name="Samba User">
    <module-class>org.safehaus.penrose.samba.SambaUserModule</module-class>
    <parameter>
      <param-name>ssh.client</param-name>
      <param-value>C:/Program Files/PuTTY/plink.exe</param-value>
    </parameter>
    <parameter>
      <param-name>samba.admin</param-name>
      <param-value>root</param-value>
    </parameter>
    <parameter>
      <param-name>samba.server</param-name>
      <param-value>linux.example.com</param-value>
    </parameter>
  </module>

  <module name="Samba Group">
    <module-class>org.safehaus.penrose.samba.SambaGroupModule</module-class>
    <parameter>
      <param-name>ssh.client</param-name>
      <param-value>C:/Program Files/PuTTY/plink.exe</param-value>
    </parameter>
    <parameter>
      <param-name>samba.admin</param-name>
      <param-value>root</param-value>
    </parameter>
    <parameter>
      <param-name>samba.server</param-name>
      <param-value>linux.example.com</param-value>
    </parameter>
  </module>

  <module-mapping>
    <module-name>Samba User</module-name>
    <base-dn>ou=Users,dc=Samba,dc=Example,dc=com</base-dn>
    <filter>(objectClass=*)</filter>
    <scope>ONELEVEL</scope>
  </module-mapping>

  <module-mapping>
    <module-name>Samba Group</module-name>
    <base-dn>ou=Groups,dc=Samba,dc=Example,dc=com</base-dn>
    <filter>(objectClass=*)</filter>
    <scope>ONELEVEL</scope>
  </module-mapping>

</modules>

=== edewata/penrose-server/samples/ldap_sync/DIR-INF/modules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>

  <module name="users">
    <module-class>org.safehaus.penrose.ldap.module.ChangeLogSyncModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>users</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>users_cache</param-value>
    </parameter>
    <parameter>
      <param-name>changelog</param-name>
      <param-value>changelog</param-value>
    </parameter>
    <parameter>
      <param-name>tracker</param-name>
      <param-value>users_tracker</param-value>
    </parameter>
  </module>

  <module name="groups">
    <module-class>org.safehaus.penrose.ldap.module.ChangeLogSyncModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>groups</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>groups_cache</param-value>
    </parameter>
    <parameter>
      <param-name>changelog</param-name>
      <param-value>changelog</param-value>
    </parameter>
    <parameter>
      <param-name>tracker</param-name>
      <param-value>groups_tracker</param-value>
    </parameter>
  </module>

</modules>

=== edewata/penrose-server/samples/ipa_samba/DIR-INF/modules-group.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>

  <module name="IPASambaGroupModule">
    <module-class>org.safehaus.penrose.ipa.module.GroupSyncModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>ipa</param-value>
    </parameter>
    <parameter>
      <param-name>sourceUsers</param-name>
      <param-value>ipa_users</param-value>
    </parameter>
    <parameter>
      <param-name>sourceGroups</param-name>
      <param-value>ipa_groups</param-value>
    </parameter>
    <parameter>
      <param-name>sourceKeyAttribute</param-name>
      <param-value>cn</param-value>
    </parameter>
    <parameter>
      <param-name>sourceLinkAttribute</param-name>
      <param-value>ntUniqueId</param-value>
    </parameter>
    <parameter>
      <param-name>targetImportGroupMapping</param-name>
      <param-value>SambaImportGroup</param-value>
    </parameter>
    <parameter>
      <param-name>sourceImportGroupMapping</param-name>
      <param-value>IPAImportGroup</param-value>
    </parameter>
    <parameter>
      <param-name>targetLinkGroupMapping</param-name>
      <param-value>SambaLinkGroup</param-value>
    </parameter>
    <parameter>
      <param-name>sourceLinkGroupMapping</param-name>
      <param-value>IPALinkGroup</param-value>
    </parameter>
    <parameter>
      <param-name>targetSyncGroupMapping</param-name>
      <param-value>SambaSyncGroup</param-value>
    </parameter>
    <parameter>
      <param-name>sourceSyncGroupMapping</param-name>
      <param-value>IPASyncGroup</param-value>
    </parameter>
    <parameter>
      <param-name>targetUnlinkGroupMapping</param-name>
      <param-value>SambaUnlinkGroup</param-value>
    </parameter>
    <parameter>
      <param-name>sourceUnlinkGroupMapping</param-name>
      <param-value>IPAUnlinkGroup</param-value>
    </parameter>
    <parameter>
      <param-name>targetAlias</param-name>
      <param-value>samba</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>sambaFE</param-value>
    </parameter>
    <parameter>
      <param-name>targetGroups</param-name>
      <param-value>sambaGroupsBE</param-value>
    </parameter>
    <parameter>
      <param-name>targetKeyAttribute</param-name>
      <param-value>sAMAccountName</param-value>
    </parameter>
    <parameter>
      <param-name>targetLinkAttribute</param-name>
      <param-value>nsUniqueId</param-value>
    </parameter>
    <parameter>
      <param-name>userSyncModule</param-name>
      <param-value>IPASambaUserModule</param-value>
    </parameter>
  </module>

</modules>

=== edewata/penrose-server/samples/lockout/DIR-INF/modules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>

  <module name="LockoutModule">
    <module-class>org.safehaus.penrose.lockout.module.LockoutModule</module-class>
    <parameter>
      <param-name>limit</param-name>
      <param-value>3</param-value>
    </parameter>
    <parameter>
      <param-name>expiration</param-name>
      <param-value>5</param-value>
    </parameter>
  </module>

  <module-mapping>
    <module-name>LockoutModule</module-name>
    <base-dn>dc=Lockout,dc=Example,dc=com</base-dn>
  </module-mapping>

</modules>

=== edewata/penrose-server/samples/samba_ipa/DIR-INF/modules-group.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>

  <module name="SambaIPAGroupModule">
    <module-class>org.safehaus.penrose.ipa.module.GroupSyncModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>samba</param-value>
    </parameter>
    <parameter>
      <param-name>sourceUsers</param-name>
      <param-value>sambaUsers</param-value>
    </parameter>
    <parameter>
      <param-name>sourceGroups</param-name>
      <param-value>sambaGroups</param-value>
    </parameter>
    <parameter>
      <param-name>sourceKeyAttribute</param-name>
      <param-value>sAMAccountName</param-value>
    </parameter>
    <parameter>
      <param-name>sourceLinkAttribute</param-name>
      <param-value>nsUniqueId</param-value>
    </parameter>
    <parameter>
      <param-name>targetImportGroupMapping</param-name>
      <param-value>IPAImportGroup</param-value>
    </parameter>
    <parameter>
      <param-name>targetSyncGroupMapping</param-name>
      <param-value>IPASyncGroup</param-value>
    </parameter>
    <parameter>
      <param-name>targetLinkGroupMapping</param-name>
      <param-value>IPALinkGroup</param-value>
    </parameter>
    <parameter>
      <param-name>targetUnlinkGroupMapping</param-name>
      <param-value>IPAUnlinkGroup</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>ipa</param-value>
    </parameter>
    <parameter>
      <param-name>targetGroups</param-name>
      <param-value>ipaGroups</param-value>
    </parameter>
    <parameter>
      <param-name>targetKeyAttribute</param-name>
      <param-value>cn</param-value>
    </parameter>
    <parameter>
      <param-name>targetLinkAttribute</param-name>
      <param-value>ntUniqueId</param-value>
    </parameter>
    <parameter>
      <param-name>userSyncModule</param-name>
      <param-value>SambaIPAUserModule</param-value>
    </parameter>
  </module>

</modules>

=== edewata/penrose-server/samples/ipa/DIR-INF/modules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules PUBLIC
  "-//Penrose/DTD Modules ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/modules.dtd">

<modules>

  <module name="users">
    <module-class>org.safehaus.penrose.ipa.module.SambaSyncModule</module-class>
    <parameter>
      <param-name>source</param-name>
      <param-value>ipa</param-value>
    </parameter>
    <parameter>
      <param-name>sourceUsers</param-name>
      <param-value>ipa_users</param-value>
    </parameter>
    <parameter>
      <param-name>sourceGroups</param-name>
      <param-value>ipa_groups</param-value>
    </parameter>
    <parameter>
      <param-name>target</param-name>
      <param-value>samba</param-value>
    </parameter>
    <parameter>
      <param-name>changelog</param-name>
      <param-value>ipa_changelog</param-value>
    </parameter>
    <parameter>
      <param-name>tracker</param-name>
      <param-value>ipa_tracker</param-value>
    </parameter>
  </module>

</modules>
