=== edewata/penrose-server/common/src/java/org/safehaus/penrose/service/service.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT service (description?, service-class, parameter*)>
<!ATTLIST service enabled CDATA #IMPLIED>

<!ELEMENT service-class (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== edewata/penrose-server/services/JMX/SERVICE-INF/service.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE service PUBLIC
  "-//Penrose/DTD Service ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/service.dtd">

<service enabled="true">

  <service-class>org.safehaus.penrose.management.PenroseJMXService</service-class>

  <parameter>
    <param-name>rmiPort</param-name>
    <param-value>1099</param-value>
  </parameter>

  <parameter>
    <param-name>rmiTransportPort</param-name>
    <param-value>40888</param-value>
  </parameter>

</service>

=== edewata/penrose-server/services/ApacheDS/SERVICE-INF/service.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE service PUBLIC
  "-//Penrose/DTD Service ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/service.dtd">

<service enabled="false">
    
  <service-class>org.safehaus.penrose.apacheds.ApacheDSService</service-class>
  
  <parameter>
    <param-name>ldapPort</param-name>
    <param-value>10389</param-value>
  </parameter>
    
  <parameter>
    <param-name>enableLdaps</param-name>
    <param-value>false</param-value>
  </parameter>
    
  <parameter>
    <param-name>ldapsPort</param-name>
    <param-value>10636</param-value>
  </parameter>
    
  <parameter>
    <param-name>ldapsCertificateFile</param-name>
    <param-value>conf/penrose.keystore</param-value>
  </parameter>
    
  <parameter>
    <param-name>ldapsCertificatePassword</param-name>
    <param-value>changeit</param-value>
  </parameter>
    
  <parameter>
    <param-name>allowAnonymousAccess</param-name>
    <param-value>true</param-value>
  </parameter>
    
</service>
