=== edewata/penrose-server/core/src/java/org/safehaus/penrose/config/server.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT server (
        system-property*,
        property*,
        schema*,
        interpreter*,
        engine*,
        handler*,
        adapter*,
        session*,
        connector*,
        root
)>

<!ELEMENT system-property (property-name, property-value)>
<!ELEMENT property-name (#PCDATA)>
<!ELEMENT property-value (#PCDATA)>

<!ELEMENT property (property-name, property-value)>

<!ELEMENT schema EMPTY>
<!ATTLIST schema name CDATA #IMPLIED>
<!ATTLIST schema path CDATA #REQUIRED>

<!ELEMENT session (description?, parameter*)>
<!ATTLIST session name CDATA #IMPLIED>

<!ELEMENT interpreter (interpreter-name?,interpreter-class?, description?, parameter*)>
<!ATTLIST interpreter name CDATA #IMPLIED>
<!ELEMENT interpreter-name (#PCDATA)>
<!ELEMENT interpreter-class (#PCDATA)>

<!ELEMENT handler (handler-name?, handler-class?, description?, parameter*)>
<!ATTLIST handler name CDATA #IMPLIED>
<!ELEMENT handler-name (#PCDATA)>
<!ELEMENT handler-class (#PCDATA)>

<!ELEMENT engine (engine-name?, engine-class?, description?, parameter*)>
<!ATTLIST engine name CDATA #IMPLIED>
<!ELEMENT engine-name (#PCDATA)>
<!ELEMENT engine-class (#PCDATA)>

<!ELEMENT connector (connector-class?, description?, parameter*)>
<!ATTLIST connector name CDATA #IMPLIED>
<!ELEMENT connector-class (#PCDATA)>

<!ELEMENT adapter (adapter-class, description?, parameter*)>
<!ATTLIST adapter name CDATA #REQUIRED>
<!ELEMENT adapter-class (#PCDATA)>

<!ELEMENT root (root-dn, root-password)>
<!ELEMENT root-dn (#PCDATA)>
<!ELEMENT root-password (#PCDATA)>

<!ELEMENT cache-class (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== edewata/penrose-server/conf/server.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE server PUBLIC
  "-//Penrose/DTD Server ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/server.dtd">

<server>

  <system-property>
    <property-name>java.rmi.server.hostname</property-name>
    <property-value>localhost</property-value>
  </system-property>

  <adapter name="JDBC">
    <adapter-class>org.safehaus.penrose.jdbc.adapter.JDBCAdapter</adapter-class>
  </adapter>

  <adapter name="LDAP">
    <adapter-class>org.safehaus.penrose.ldap.adapter.LDAPAdapter</adapter-class>
  </adapter>

  <adapter name="NIS">
    <adapter-class>org.safehaus.penrose.nis.adapter.NISAdapter</adapter-class>
  </adapter>

  <root>
    <root-dn>uid=admin,ou=system</root-dn>
    <root-password>secret</root-password>
  </root>

</server>
