=== edewata/penrose-server/common/src/java/org/safehaus/penrose/connection/connections.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT connections (connection*)>

<!ELEMENT connection (connection-class?, description?, adapter-name?, parameter*)>
<!ATTLIST connection name CDATA #REQUIRED>

<!ELEMENT connection-class (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT adapter-name (#PCDATA)>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== edewata/penrose-server/samples/federation/templates/ldap/DIR-INF/connections.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE connections PUBLIC
  "-//Penrose/DTD Connections ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/connections.dtd">

<connections>

  <connection name="LDAP">
    <adapter-name>LDAP</adapter-name>
    <parameter>
      <param-name>java.naming.provider.url</param-name>
      <param-value>${ldap.url}</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.principal</param-name>
      <param-value>${ldap.user}</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.credentials</param-name>
      <param-value>${ldap.password}</param-value>
    </parameter>
  </connection>

</connections>

=== edewata/penrose-server/samples/ldap_sync/DIR-INF/connections.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE connections PUBLIC
  "-//Penrose/DTD Connections ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/connections.dtd">

<connections>

  <connection name="Source">
    <adapter-name>LDAP</adapter-name>
    <parameter>
      <param-name>java.naming.provider.url</param-name>
      <param-value>ldap://localhost:1389/</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.principal</param-name>
      <param-value>cn=Directory Manager</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.credentials</param-name>
      <param-value>secret123</param-value>
    </parameter>
  </connection>

  <connection name="Cache">
    <adapter-name>LDAP</adapter-name>
    <parameter>
      <param-name>java.naming.provider.url</param-name>
      <param-value>ldap://localhost/</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.principal</param-name>
      <param-value>cn=Manager,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.credentials</param-name>
      <param-value>secret</param-value>
    </parameter>
  </connection>

  <connection name="Tracker">
    <adapter-name>JDBC</adapter-name>
    <parameter>
      <param-name>driver</param-name>
      <param-value>com.mysql.jdbc.Driver</param-value>
    </parameter>
    <parameter>
      <param-name>url</param-name>
      <param-value>jdbc:mysql://localhost/ldap_sync?autoReconnect=true</param-value>
    </parameter>
    <parameter>
      <param-name>user</param-name>
      <param-value>penrose</param-value>
    </parameter>
    <parameter>
      <param-name>password</param-name>
      <param-value>penrose</param-value>
    </parameter>
  </connection>

</connections>
