=== edewata/penrose-server/common/src/java/org/safehaus/penrose/connection/connections.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT connections (connection*)>

<!ELEMENT connection (connection-class?, description?, adapter-name?, parameter*)>
<!ATTLIST connection name CDATA #REQUIRED>

<!ELEMENT connection-class (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT adapter-name (#PCDATA)>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== edewata/penrose-server/samples/nis/DIR-INF/connections.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE connections PUBLIC
  "-//Penrose/DTD Connections ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/connections.dtd">

<connections>

  <connection name="NIS">
    <adapter-name>NIS</adapter-name>
    <parameter>
      <param-name>java.naming.factory.initial</param-name>
      <param-value>com.sun.jndi.nis.NISCtxFactory</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.provider.url</param-name>
      <param-value>nis://localhost/example.com</param-value>
    </parameter>
    <parameter>
      <param-name>com.sun.jndi.nis.mailaliases</param-name>
      <param-value>nonull</param-value>
    </parameter>
    <parameter>
      <param-name>method</param-name>
      <param-value>yp</param-value>
    </parameter>
  </connection>

</connections>

=== edewata/penrose-server/samples/activeDirectory/DIR-INF/connections.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE connections PUBLIC
  "-//Penrose/DTD Connections ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/connections.dtd">

<connections>

  <connection name="Active Directory">
    <adapter-name>LDAP</adapter-name>
    <parameter>
      <param-name>java.naming.provider.url</param-name>
      <param-value>ldap://localhost/</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.principal</param-name>
      <param-value>cn=Administrator,cn=Users,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.credentials</param-name>
      <param-value>secret</param-value>
    </parameter>
  </connection>

</connections>

=== edewata/penrose-server/samples/ipa_samba/DIR-INF/connections.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE connections PUBLIC
  "-//Penrose/DTD Connections ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/connections.dtd">

<connections>

  <connection name="IPA">
    <adapter-name>LDAP</adapter-name>
    <parameter>
      <param-name>java.naming.provider.url</param-name>
      <param-value>ldap://ipa.example.com/</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.principal</param-name>
      <param-value>uid=sync,cn=sysaccounts,cn=etc,dc=example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.credentials</param-name>
      <param-value>Secret123</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.ldap.attributes.binary</param-name>
      <param-value>krbPrincipalKey userPassword</param-value>
    </parameter>
  </connection>

  <connection name="SambaFE">
    <adapter-name>LDAP</adapter-name>
    <parameter>
      <param-name>java.naming.provider.url</param-name>
      <param-value>ldap://samba.example.com/</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.principal</param-name>
      <param-value>CN=Sync,CN=Users,DC=samba,DC=example,DC=com</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.credentials</param-name>
      <param-value>Secret123</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.ldap.attributes.binary</param-name>
      <param-value>
          objectGUID objectSid ntPwdHistory lmPwdHistory nTSecurityDescriptor
          supplementalCredentials unicodePwd
      </param-value>
    </parameter>
  </connection>

  <connection name="SambaBE">
    <adapter-name>LDAP</adapter-name>
    <parameter>
      <param-name>java.naming.provider.url</param-name>
      <param-value>ldap://samba.example.com:1389/</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.principal</param-name>
      <param-value>CN=Manager,DC=samba,DC=example,DC=com</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.credentials</param-name>
      <param-value>Secret123</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.ldap.attributes.binary</param-name>
      <param-value>
          ntPwdHistory lmPwdHistory nTSecurityDescriptor
          supplementalCredentials unicodePwd
      </param-value>
    </parameter>
  </connection>

  <connection name="Database">
    <adapter-name>JDBC</adapter-name>
    <parameter>
      <param-name>driver</param-name>
      <param-value>org.hsqldb.jdbcDriver</param-value>
    </parameter>
    <parameter>
      <param-name>url</param-name>
      <param-value>jdbc:hsqldb:file:partitions/ipa_samba/db/example</param-value>
    </parameter>
    <parameter>
      <param-name>user</param-name>
      <param-value>sa</param-value>
    </parameter>
    <parameter>
      <param-name>password</param-name>
      <param-value></param-value>
    </parameter>
    <parameter>
      <param-name>shutdown</param-name>
      <param-value>true</param-value>
    </parameter>
  </connection>

</connections>

=== edewata/penrose-server/samples/module/DIR-INF/connections.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE connections PUBLIC
  "-//Penrose/DTD Connections ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/connections.dtd">

<connections>

  <connection name="Database">
    <adapter-name>JDBC</adapter-name>
    <parameter>
      <param-name>driver</param-name>
      <param-value>org.hsqldb.jdbcDriver</param-value>
    </parameter>
    <parameter>
      <param-name>url</param-name>
      <param-value>jdbc:hsqldb:file:partitions/module/db/example</param-value>
    </parameter>
    <parameter>
      <param-name>user</param-name>
      <param-value>sa</param-value>
    </parameter>
    <parameter>
      <param-name>password</param-name>
      <param-value></param-value>
    </parameter>
    <parameter>
      <param-name>shutdown</param-name>
      <param-value>true</param-value>
    </parameter>
  </connection>

</connections>

=== edewata/penrose-server/samples/unix/DIR-INF/connections.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE connections PUBLIC
  "-//Penrose/DTD Connections ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/connections.dtd">

<connections>

  <connection name="NIS">
    <adapter-name>NIS</adapter-name>
    <parameter>
      <param-name>method</param-name>
      <param-value>local</param-value>
    </parameter>
    <parameter>
      <param-name>dir</param-name>
      <param-value>/etc</param-value>
    </parameter>
  </connection>

</connections>

=== edewata/penrose-server/samples/join/DIR-INF/connections.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE connections PUBLIC
  "-//Penrose/DTD Connections ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/connections.dtd">

<connections>

  <connection name="Database">
    <adapter-name>JDBC</adapter-name>
    <parameter>
      <param-name>driver</param-name>
      <param-value>org.hsqldb.jdbcDriver</param-value>
    </parameter>
    <parameter>
      <param-name>url</param-name>
      <param-value>jdbc:hsqldb:file:partitions/join/db/example</param-value>
    </parameter>
    <parameter>
      <param-name>user</param-name>
      <param-value>sa</param-value>
    </parameter>
    <parameter>
      <param-name>password</param-name>
      <param-value></param-value>
    </parameter>
    <parameter>
      <param-name>shutdown</param-name>
      <param-value>true</param-value>
    </parameter>
  </connection>

  <connection name="Directory">
    <adapter-name>LDAP</adapter-name>
    <parameter>
      <param-name>java.naming.provider.url</param-name>
      <param-value>ldap://localhost/</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.principal</param-name>
      <param-value>cn=Manager,dc=my-domain,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.credentials</param-name>
      <param-value>secret</param-value>
    </parameter>
  </connection>

</connections>

=== edewata/penrose-server/samples/samba/DIR-INF/connections.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE connections PUBLIC
  "-//Penrose/DTD Connections ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/connections.dtd">

<connections>

  <connection name="Database">
    <adapter-name>JDBC</adapter-name>
    <parameter>
      <param-name>driver</param-name>
      <param-value>com.mysql.jdbc.Driver</param-value>
    </parameter>
    <parameter>
      <param-name>url</param-name>
      <param-value>jdbc:mysql://localhost/samba?autoReconnect=true</param-value>
    </parameter>
    <parameter>
      <param-name>user</param-name>
      <param-value>penrose</param-value>
    </parameter>
    <parameter>
      <param-name>password</param-name>
      <param-value>penrose</param-value>
    </parameter>
  </connection>
    
</connections>

=== edewata/penrose-server/samples/ad_schema/DIR-INF/connections.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE connections PUBLIC
  "-//Penrose/DTD Connections ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/connections.dtd">

<connections>

  <connection name="Active Directory">
    <adapter-name>LDAP</adapter-name>
    <parameter>
      <param-name>java.naming.provider.url</param-name>
      <param-value>ldap://server1/</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.principal</param-name>
      <param-value>cn=Administrator,cn=Users,dc=AD,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>java.naming.security.credentials</param-name>
      <param-value>secret</param-value>
    </parameter>
    <parameter>
      <param-name>pageSize</param-name>
      <param-value>100</param-value>
    </parameter>
  </connection>

</connections>
