=== edewata/penrose-server/common/src/java/org/safehaus/penrose/source/sources.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT sources (source*)>

<!ELEMENT source (source-class?, description?, partition-name?, connection-name?, field*, parameter*)>
<!ATTLIST source name CDATA #REQUIRED>

<!ELEMENT source-class (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT partition-name (#PCDATA)>
<!ELEMENT connection-name (#PCDATA)>

<!ELEMENT field (binary|constant|variable|expression)>
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field originalName CDATA #IMPLIED>
<!ATTLIST field primaryKey (true|first|false) "false">
<!ATTLIST field type CDATA #IMPLIED>
<!ATTLIST field originalType CDATA #IMPLIED>
<!ATTLIST field castType CDATA #IMPLIED>
<!ATTLIST field length CDATA #IMPLIED>
<!ATTLIST field precision CDATA #IMPLIED>
<!ATTLIST field searchable CDATA #IMPLIED>
<!ATTLIST field unique CDATA #IMPLIED>
<!ATTLIST field index CDATA #IMPLIED>
<!ATTLIST field caseSensitive CDATA #IMPLIED>
<!ATTLIST field autoIncrement CDATA #IMPLIED>

<!ELEMENT binary (#PCDATA)>
<!ELEMENT constant (#PCDATA)>
<!ELEMENT variable (#PCDATA)>
<!ELEMENT expression (#PCDATA)>
<!ATTLIST expression foreach CDATA #IMPLIED>
<!ATTLIST expression var CDATA #IMPLIED>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== edewata/penrose-server/samples/ad_schema/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="ad_schema">
    <connection-name>Active Directory</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>cn=Schema,cn=Configuration,dc=AD,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>newBaseDn</param-name>
      <param-value>cn=AD Style,dc=AD Schema,dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="ldap_schema">
    <connection-name>Active Directory</connection-name>
    <field name="lDAPDisplayName" primaryKey="true"/>
    <field name="objectClass"/>
    <field name="attributeID"/>
    <field name="adminDescription"/>
    <field name="attributeSyntax"/>
    <field name="isSingleValued"/>
    <field name="governsID"/>
    <field name="mustContain"/>
    <field name="systemMustContain"/>
    <field name="mayContain"/>
    <field name="systemMayContain"/>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>cn=Schema,cn=Configuration,dc=AD,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
  </source>

</sources>

=== edewata/penrose-server/samples/hsqldb/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>Database</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>users</param-value>
    </parameter>
    <parameter>
      <param-name>create</param-name>
      <param-value>true</param-value>
    </parameter>
  </source>

  <source name="groups">
    <connection-name>Database</connection-name>
    <field name="groupname" primaryKey="true"/>
    <field name="description"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>groups</param-value>
    </parameter>
    <parameter>
      <param-name>create</param-name>
      <param-value>true</param-value>
    </parameter>
  </source>

</sources>

=== edewata/penrose-server/samples/ldap/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>LDAP</connection-name>
    <field name="uid" primaryKey="true"/>
    <field name="cn"/>
    <field name="sn"/>
    <field name="userPassword"/>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Users,dc=my-domain,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>person,organizationalPerson,inetOrgPerson</param-value>
    </parameter>
  </source>

  <source name="groups">
    <connection-name>LDAP</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="description"/>
    <field name="uniqueMember"/>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Groups,dc=my-domain,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=*)</param-value>
    </parameter>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>groupOfUniqueNames</param-value>
    </parameter>
  </source>

</sources>

=== edewata/penrose-server/samples/ad_merge/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="source1">
    <connection-name>LDAP1</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>dc=ad,dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="source2">
    <connection-name>LDAP2</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>dc=ad,dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="mergedSource">
    <source-class>org.safehaus.penrose.source.MergeSource</source-class>
    <parameter>
      <param-name>sources</param-name>
      <param-value>source1,source2</param-value>
    </parameter>
    <parameter>
      <param-name>mapAttributes</param-name>
      <param-value>member</param-value>
    </parameter>
  </source>

</sources>

=== edewata/penrose-server/samples/operational/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>MySQL</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <field name="creatorsName"/>
    <field name="createTimestamp" type="DATETIME"/>
    <field name="modifiersName"/>
    <field name="modifyTimestamp" type="DATETIME"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>users</param-value>
    </parameter>
  </source>

</sources>

=== edewata/penrose-server/samples/nested/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>MySQL</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="encPassword"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>users</param-value>
    </parameter>
  </source>

  <source name="groups">
    <connection-name>MySQL</connection-name>
    <field name="groupname" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>groups</param-value>
    </parameter>
  </source>

  <source name="usergroups">
    <connection-name>MySQL</connection-name>
    <field name="groupname" primaryKey="true"/>
    <field name="username" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>usergroups</param-value>
    </parameter>
  </source>

</sources>

=== edewata/penrose-server/samples/unix/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>NIS</connection-name>
    <field name="uid" primaryKey="true"/>
    <field name="uidNumber"/>
    <field name="gidNumber"/>
    <field name="homeDirectory"/>
    <field name="userPassword"/>
    <field name="loginShell"/>
    <field name="gecos"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>posixAccount</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>passwd</param-value>
    </parameter>
  </source>

  <source name="groups">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="gidNumber"/>
    <field name="userPassword"/>
    <field name="memberUid"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>posixGroup</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>group</param-value>
    </parameter>
  </source>

  <source name="hosts">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="ipHostNumber"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>ipHost</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>hosts</param-value>
    </parameter>
  </source>

  <source name="services">
    <connection-name>NIS</connection-name>
    <field name="cn"/>
    <field name="ipServicePort" primaryKey="true"/>
    <field name="ipServiceProtocol" primaryKey="true"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>ipService</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>services</param-value>
    </parameter>
  </source>

  <source name="rpcs">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="oncRpcNumber"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>oncRpc</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>rpc</param-value>
    </parameter>
  </source>

  <source name="netids">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="nisNetIdUser"/>
    <field name="nisNetIdGroup"/>
    <field name="nisNetIdHost"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>nisNetId</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>netid</param-value>
    </parameter>
  </source>

  <source name="protocols">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="ipProtocolNumber"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>ipProtocol</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>protocols</param-value>
    </parameter>
  </source>

  <source name="aliases">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="rfc822mailMember" originalName="mail"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>nisMailAlias</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>aliases</param-value>
    </parameter>
  </source>

  <source name="netgroups">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="nisNetgroupTriple"/>
    <field name="memberNisNetgroup"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>nisNetgroup</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>netgroup</param-value>
    </parameter>
  </source>

  <source name="ethers">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="macAddress"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>ieee802Device</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>ethers</param-value>
    </parameter>
  </source>

  <source name="bootparams">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="bootFile"/>
    <field name="bootParameter"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>bootableDevice</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>bootparams</param-value>
    </parameter>
  </source>

  <source name="networks">
    <connection-name>NIS</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="ipNetworkNumber"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>ipNetwork</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>networks</param-value>
    </parameter>
  </source>

  <source name="automounts">
    <source-class>org.safehaus.penrose.nis.source.NISAutomountsSource</source-class>
    <connection-name>NIS</connection-name>
    <field name="automountMapName" primaryKey="true"/>
    <field name="automountKey" primaryKey="true"/>
    <field name="automountInformation"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>automount</param-value>
    </parameter>
    <parameter>
      <param-name>base</param-name>
      <param-value>auto.master</param-value>
    </parameter>
  </source>

</sources>

=== edewata/penrose-server/samples/samba_ipa/DIR-INF/sources-samba.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="samba">
    <connection-name>SambaBE</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>DC=samba,DC=example,DC=com</param-value>
    </parameter>
  </source>

  <source name="samba_users">
    <connection-name>SambaBE</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>DC=samba,DC=example,DC=com</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(&amp;(objectClass=user)(!(objectClass=computer))(!(servicePrincipalName=*)))</param-value>
    </parameter>
    <parameter>
      <param-name>attributes</param-name>
      <param-value>objectClass cn sn sAMAccountName
          homeDirectory accountExpires pwdLastSet
          sambaSID lastLogon scriptPath
          profilePath logonCount badPwdCount primaryGroupID
          userAccountControl nsUniqueId supplementalCredentials
      </param-value>
    </parameter>
  </source>

  <source name="samba_groups">
    <connection-name>SambaBE</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>DC=samba,DC=example,DC=com</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=group)</param-value>
    </parameter>
  </source>

  <source name="samba_hosts">
    <connection-name>SambaBE</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>DC=samba,DC=example,DC=com</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=computer)</param-value>
    </parameter>
  </source>

</sources>
