=== edewata/penrose-server/common/src/java/org/safehaus/penrose/source/sources.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT sources (source*)>

<!ELEMENT source (source-class?, description?, partition-name?, connection-name?, field*, parameter*)>
<!ATTLIST source name CDATA #REQUIRED>

<!ELEMENT source-class (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT partition-name (#PCDATA)>
<!ELEMENT connection-name (#PCDATA)>

<!ELEMENT field (binary|constant|variable|expression)>
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field originalName CDATA #IMPLIED>
<!ATTLIST field primaryKey (true|first|false) "false">
<!ATTLIST field type CDATA #IMPLIED>
<!ATTLIST field originalType CDATA #IMPLIED>
<!ATTLIST field castType CDATA #IMPLIED>
<!ATTLIST field length CDATA #IMPLIED>
<!ATTLIST field precision CDATA #IMPLIED>
<!ATTLIST field searchable CDATA #IMPLIED>
<!ATTLIST field unique CDATA #IMPLIED>
<!ATTLIST field index CDATA #IMPLIED>
<!ATTLIST field caseSensitive CDATA #IMPLIED>
<!ATTLIST field autoIncrement CDATA #IMPLIED>

<!ELEMENT binary (#PCDATA)>
<!ELEMENT constant (#PCDATA)>
<!ELEMENT variable (#PCDATA)>
<!ELEMENT expression (#PCDATA)>
<!ATTLIST expression foreach CDATA #IMPLIED>
<!ATTLIST expression var CDATA #IMPLIED>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== edewata/penrose-server/samples/federation/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="Global">

    <connection-name>LDAP</connection-name>

    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Global,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>

  </source>

  <source name="NIS">

    <connection-name>LDAP</connection-name>

    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=NIS,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>

  </source>

  <source name="users">

    <connection-name>LDAP</connection-name>

    <field name="dn" primaryKey="true"/>

    <!-- account -->
    <field name="uid"/>
    <field name="description"/>
    <field name="seeAlso"/>
    <field name="l"/>
    <field name="o"/>
    <field name="ou"/>
    <field name="host"/>

    <!-- posixAccount -->
    <field name="cn"/>
    <field name="uidNumber"/>
    <field name="gidNumber"/>
    <field name="homeDirectory"/>
    <field name="userPassword"/>
    <field name="loginShell"/>
    <field name="gecos"/>

    <!-- shadowAccount -->
    <field name="shadowLastChange"/>
    <field name="shadowMin"/>
    <field name="shadowMax"/>
    <field name="shadowWarning"/>
    <field name="shadowInactive"/>
    <field name="shadowExpire"/>
    <field name="shadowFlag"/>

    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>account,posixAccount,shadowAccount</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Users,ou=Global,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>

  </source>

  <source name="groups">

    <connection-name>LDAP</connection-name>

    <field name="dn" primaryKey="true"/>

    <field name="cn"/>
    <field name="gidNumber"/>
    <field name="userPassword"/>
    <field name="memberUid"/>
    <field name="description"/>
    <field name="seeAlso"/>

    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>posixGroup</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Groups,ou=Global,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>

  </source>

</sources>

=== edewata/penrose-server/samples/jdbc_sync/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>Source</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>users</param-value>
    </parameter>
  </source>

  <source name="users_changelog">
    <connection-name>Source</connection-name>
    <field name="changeNumber" type="INTEGER" autoIncrement="true" primaryKey="true"/>
    <field name="changeTime" type="DATETIME"/>
    <field name="changeAction"/>
    <field name="changeUser"/>
    <field name="username"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>users_changelog</param-value>
    </parameter>
  </source>

  <source name="groups">
    <connection-name>Source</connection-name>
    <field name="groupname" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>groups</param-value>
    </parameter>
  </source>

  <source name="groups_changelog">
    <connection-name>Source</connection-name>
    <field name="changeNumber" type="INTEGER" autoIncrement="true" primaryKey="true"/>
    <field name="changeTime" type="DATETIME"/>
    <field name="changeAction"/>
    <field name="changeUser"/>
    <field name="groupname"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>groups_changelog</param-value>
    </parameter>
  </source>

  <source name="usergroups">
    <connection-name>Source</connection-name>
    <field name="groupname" primaryKey="true"/>
    <field name="username" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>usergroups</param-value>
    </parameter>
  </source>

  <source name="usergroups_changelog">
    <connection-name>Source</connection-name>
    <field name="changeNumber" type="INTEGER" autoIncrement="true" primaryKey="true"/>
    <field name="changeTime" type="DATETIME"/>
    <field name="changeAction"/>
    <field name="changeUser"/>
    <field name="groupname" primaryKey="true"/>
    <field name="username" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>usergroups_changelog</param-value>
    </parameter>
  </source>

  <source name="users_cache">
    <connection-name>Cache</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>users_cache</param-value>
    </parameter>
  </source>

  <source name="users_tracker">
    <connection-name>Cache</connection-name>
    <field name="changeNumber" type="INTEGER" primaryKey="true"/>
    <field name="changeTimestamp" type="DATETIME"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>users_tracker</param-value>
    </parameter>
  </source>

  <source name="groups_cache">
    <connection-name>Cache</connection-name>
    <field name="groupname" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>groups_cache</param-value>
    </parameter>
  </source>

  <source name="groups_tracker">
    <connection-name>Cache</connection-name>
    <field name="changeNumber" type="INTEGER" primaryKey="true"/>
    <field name="changeTimestamp" type="DATETIME"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>groups_tracker</param-value>
    </parameter>
  </source>

  <source name="usergroups_cache">
    <connection-name>Cache</connection-name>
    <field name="groupname" primaryKey="true"/>
    <field name="username" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>usergroups_cache</param-value>
    </parameter>
  </source>

  <source name="usergroups_tracker">
    <connection-name>Cache</connection-name>
    <field name="changeNumber" type="INTEGER" primaryKey="true"/>
    <field name="changeTimestamp" type="DATETIME"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>usergroups_tracker</param-value>
    </parameter>
  </source>

</sources>

=== edewata/penrose-server/samples/encryption/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="plain">
    <connection-name>Database</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>plain</param-value>
    </parameter>
  </source>

  <source name="crypt">
    <connection-name>Database</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>crypt</param-value>
    </parameter>
  </source>

  <source name="crypt_md5">
    <connection-name>Database</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>crypt_md5</param-value>
    </parameter>
  </source>

  <source name="crypt_sha256">
    <connection-name>Database</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>crypt_sha256</param-value>
    </parameter>
  </source>

  <source name="crypt_sha512">
    <connection-name>Database</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>crypt_sha512</param-value>
    </parameter>
  </source>

  <source name="md5">
    <connection-name>Database</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>md5</param-value>
    </parameter>
  </source>

  <source name="sha">
    <connection-name>Database</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>sha</param-value>
    </parameter>
  </source>

</sources>

=== edewata/penrose-server/samples/federation/templates/nis/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="LDAP">
    <partition-name>federation</partition-name>
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=${nis.name},ou=NIS,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="users">
    <partition-name>federation</partition-name>
    <connection-name>LDAP</connection-name>
    <field name="dn" primaryKey="true"/>
    <field name="uid"/>
    <field name="seeAlso"/>
    <field name="cn"/>
    <field name="uidNumber"/>
    <field name="gidNumber"/>
    <field name="homeDirectory"/>
    <field name="userPassword"/>
    <field name="loginShell"/>
    <field name="gecos"/>
    <field name="description"/>
    <field name="shadowLastChange"/>
    <field name="shadowMin"/>
    <field name="shadowMax"/>
    <field name="shadowWarning"/>
    <field name="shadowInactive"/>
    <field name="shadowExpire"/>
    <field name="shadowFlag"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>account,posixAccount,shadowAccount</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Users,ou=${nis.name},ou=NIS,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
  </source>

  <source name="groups">
    <partition-name>federation</partition-name>
    <connection-name>LDAP</connection-name>
    <field name="dn" primaryKey="true"/>
    <field name="cn"/>
    <field name="gidNumber"/>
    <field name="userPassword"/>
    <field name="memberUid"/>
    <field name="description"/>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>posixGroup</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Groups,ou=${nis.name},ou=NIS,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
  </source>

  <source name="hosts">
    <partition-name>federation</partition-name>
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Hosts,ou=${nis.name},ou=NIS,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="services">
    <partition-name>federation</partition-name>
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Services,ou=${nis.name},ou=NIS,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="rpcs">
    <partition-name>federation</partition-name>
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=RPCs,ou=${nis.name},ou=NIS,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="netids">
    <partition-name>federation</partition-name>
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=NetIDs,ou=${nis.name},ou=NIS,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="protocols">
    <partition-name>federation</partition-name>
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Protocols,ou=${nis.name},ou=NIS,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="aliases">
    <partition-name>federation</partition-name>
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Aliases,ou=${nis.name},ou=NIS,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="netgroups">
    <partition-name>federation</partition-name>
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Netgroups,ou=${nis.name},ou=NIS,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="ethers">
    <partition-name>federation</partition-name>
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Ethers,ou=${nis.name},ou=NIS,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="bootparams">
    <partition-name>federation</partition-name>
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=BootParams,ou=${nis.name},ou=NIS,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="networks">
    <partition-name>federation</partition-name>
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Networks,ou=${nis.name},ou=NIS,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="automounts">
    <partition-name>federation</partition-name>
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Automounts,ou=${nis.name},ou=NIS,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="profiles">
    <partition-name>federation</partition-name>
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Profiles,ou=${nis.name},ou=NIS,dc=Federation,dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="errors">
    <connection-name>Database</connection-name>
    <field name="id" type="INTEGER" primaryKey="true" autoIncrement="true"
        originalType="INTEGER generated by default as identity"/>
    <field name="time" type="DATETIME"/>
    <field name="title" type="TEXT" originalType="VARCHAR"/>
    <field name="description" type="TEXT" originalType="VARCHAR"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>errors</param-value>
    </parameter>
    <parameter>
      <param-name>create</param-name>
      <param-value>true</param-value>
    </parameter>
  </source>

</sources>

=== edewata/penrose-server/samples/ipa_samba/DIR-INF/sources-changelog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="ipa_changelog">
    <connection-name>IPA</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>cn=changelog</param-value>
    </parameter>
  </source>

  <source name="ipa_tracker">
    <connection-name>Database</connection-name>
    <field name="changeNumber" type="INTEGER" primaryKey="true"/>
    <field name="changeTimestamp" type="DATETIME"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>ipa_tracker</param-value>
    </parameter>
    <parameter>
      <param-name>create</param-name>
      <param-value>true</param-value>
    </parameter>
  </source>

</sources>

=== edewata/penrose-server/samples/ldap_sync/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>Source</connection-name>
    <field name="uid" primaryKey="true"/>
    <field name="cn"/>
    <field name="sn"/>
    <field name="userPassword"/>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Users,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>person,organizationalPerson,inetOrgPerson</param-value>
    </parameter>
  </source>

  <source name="groups">
    <connection-name>Source</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="uniqueMember"/>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Groups,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>groupOfUniqueNames</param-value>
    </parameter>
  </source>

  <source name="changelog">
    <connection-name>Source</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>cn=changelog</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
  </source>

  <source name="users_cache">
    <connection-name>Cache</connection-name>
    <field name="uid" primaryKey="true"/>
    <field name="cn"/>
    <field name="sn"/>
    <field name="userPassword"/>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Users,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>person,organizationalPerson,inetOrgPerson</param-value>
    </parameter>
  </source>

  <source name="groups_cache">
    <connection-name>Cache</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="uniqueMember"/>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Groups,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>groupOfUniqueNames</param-value>
    </parameter>
  </source>

  <source name="users_tracker">
    <connection-name>Tracker</connection-name>
    <field name="changeNumber" type="INTEGER" primaryKey="true"/>
    <field name="changeTimestamp" type="DATETIME"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>users_tracker</param-value>
    </parameter>
  </source>

  <source name="groups_tracker">
    <connection-name>Tracker</connection-name>
    <field name="changeNumber" type="INTEGER" primaryKey="true"/>
    <field name="changeTimestamp" type="DATETIME"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>groups_tracker</param-value>
    </parameter>
  </source>

</sources>

=== edewata/penrose-server/samples/changelog/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>MySQL</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>users</param-value>
    </parameter>
  </source>

  <source name="groups">
    <connection-name>MySQL</connection-name>
    <field name="groupname" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>groups</param-value>
    </parameter>
  </source>

  <source name="usergroups">
    <connection-name>MySQL</connection-name>
    <field name="groupname" primaryKey="true"/>
    <field name="username" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>usergroups</param-value>
    </parameter>
  </source>

  <source name="changelog">
    <connection-name>ChangeLog</connection-name>
    <field name="changeNumber" type="INTEGER" primaryKey="true" autoIncrement="true"/>
    <field name="targetDN" type="TEXT"/>
    <field name="changeType" type="VARCHAR" length="255"/>
    <field name="changes" type="TEXT"/>
    <field name="newRDN" type="TEXT"/>
    <field name="deleteOldRDN" type="BOOLEAN"/>
    <field name="newSuperior" type="TEXT"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>changelog</param-value>
    </parameter>
  </source>

</sources>

=== edewata/penrose-server/samples/activeDirectory/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>Active Directory</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="sn"/>
    <field name="sAMAccountName"/>
    <field name="unicodePwd"/>
    <field name="userAccountControl"/>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>cn=Users,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=user)</param-value>
    </parameter>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>user</param-value>
    </parameter>
    <parameter>
      <param-name>authentication</param-name>
      <param-value>full</param-value>
    </parameter>
  </source>

  <source name="groups">
    <connection-name>Active Directory</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="member"/>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>cn=Users,dc=Example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=group)</param-value>
    </parameter>
    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>group</param-value>
    </parameter>
  </source>

</sources>
