=== edewata/penrose-server/common/src/java/org/safehaus/penrose/source/sources.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT sources (source*)>

<!ELEMENT source (source-class?, description?, partition-name?, connection-name?, field*, parameter*)>
<!ATTLIST source name CDATA #REQUIRED>

<!ELEMENT source-class (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT partition-name (#PCDATA)>
<!ELEMENT connection-name (#PCDATA)>

<!ELEMENT field (binary|constant|variable|expression)>
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field originalName CDATA #IMPLIED>
<!ATTLIST field primaryKey (true|first|false) "false">
<!ATTLIST field type CDATA #IMPLIED>
<!ATTLIST field originalType CDATA #IMPLIED>
<!ATTLIST field castType CDATA #IMPLIED>
<!ATTLIST field length CDATA #IMPLIED>
<!ATTLIST field precision CDATA #IMPLIED>
<!ATTLIST field searchable CDATA #IMPLIED>
<!ATTLIST field unique CDATA #IMPLIED>
<!ATTLIST field index CDATA #IMPLIED>
<!ATTLIST field caseSensitive CDATA #IMPLIED>
<!ATTLIST field autoIncrement CDATA #IMPLIED>

<!ELEMENT binary (#PCDATA)>
<!ELEMENT constant (#PCDATA)>
<!ELEMENT variable (#PCDATA)>
<!ELEMENT expression (#PCDATA)>
<!ATTLIST expression foreach CDATA #IMPLIED>
<!ATTLIST expression var CDATA #IMPLIED>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== edewata/penrose-server/samples/outlook/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">

    <connection-name>Database</connection-name>

    <field name="username" primaryKey="true"/>

    <field name="firstName"/>
    <field name="initials"/>
    <field name="lastName"/>

    <field name="title"/>
    <field name="company"/>
    <field name="department"/>
    <field name="office"/>
    <field name="assistant"/>

    <field name="address"/>
    <field name="city"/>
    <field name="state"/>
    <field name="zipCode"/>
    <field name="country"/>

    <field name="businessPhone"/>
    <field name="businessPhone2"/>
    <field name="businessFax"/>
    <field name="assistantPhone"/>
    <field name="homePhone"/>
    <field name="mobile"/>
    <field name="pager"/>

    <field name="notes"/>

    <field name="password"/>

    <parameter>
      <param-name>table</param-name>
      <param-value>users</param-value>
    </parameter>

  </source>

  <source name="relationships">

    <connection-name>Database</connection-name>

    <field name="manager" primaryKey="true"/>
    <field name="report" primaryKey="true"/>

    <parameter>
      <param-name>table</param-name>
      <param-value>relationships</param-value>
    </parameter>

  </source>

</sources>

=== edewata/penrose-server/samples/ipa_samba/DIR-INF/sources-samba.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="sambaFE">
    <connection-name>SambaFE</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>DC=samba,DC=example,DC=com</param-value>
    </parameter>
  </source>

  <source name="sambaUsersFE">
    <connection-name>SambaFE</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>DC=samba,DC=example,DC=com</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(&amp;(objectClass=user)(!(objectClass=computer))(!(servicePrincipalName=*)))</param-value>
    </parameter>
    <parameter>
      <param-name>attributes</param-name>
      <param-value>
          objectClass cn sn sAMAccountName
          homeDirectory accountExpires pwdLastSet
          objectSid lastLogon scriptPath
          profilePath logonCount badPwdCount primaryGroupID
          userAccountControl objectGUID supplementalCredentials
      </param-value>
    </parameter>
  </source>

  <source name="sambaUsersBE">
    <connection-name>SambaBE</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>DC=samba,DC=example,DC=com</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(&amp;(objectClass=user)(!(objectClass=computer))(!(servicePrincipalName=*)))</param-value>
    </parameter>
    <parameter>
      <param-name>attributes</param-name>
      <param-value>
          objectClass cn sn sAMAccountName
          sambaHomePath accountExpires sambaPwdLastSet
          sambaSID lastLogon scriptPath
          sambaProfilePath logonCount badPwdCount primaryGroupID
          userAccountControl nsUniqueId supplementalCredentials
      </param-value>
    </parameter>
  </source>

  <source name="samba_groups">
    <connection-name>SambaBE</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>DC=samba,DC=example,DC=com</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=group)</param-value>
    </parameter>
  </source>

  <source name="samba_hosts">
    <connection-name>SambaBE</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>DC=samba,DC=example,DC=com</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=computer)</param-value>
    </parameter>
  </source>

</sources>

=== edewata/penrose-server/samples/lockout/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>LDAP</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Users,dc=my-domain,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>newBaseDn</param-name>
      <param-value>ou=Users,dc=Lockout,dc=Example,dc=com</param-value>
    </parameter>
  </source>

  <source name="locks">
    <connection-name>JDBC</connection-name>
    <field name="account" primaryKey="true"/>
    <field name="counter" type="INTEGER"/>
    <field name="timestamp" type="DATETIME"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>locks</param-value>
    </parameter>
  </source>

</sources>

=== edewata/penrose-server/samples/federation/templates/ldap/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="LDAP">

    <connection-name>LDAP</connection-name>

    <parameter>
      <param-name>baseDn</param-name>
      <param-value>${ldap.suffix}</param-value>
    </parameter>

  </source>
    
  <source name="users">

    <connection-name>LDAP</connection-name>

    <field name="dn" primaryKey="true"/>

    <!-- person -->
    <field name="sn"/>
    <field name="cn"/>
    <field name="userPassword"/>
    <field name="telephoneNumber"/>
    <field name="description"/>

    <!-- organizationalPerson -->
    <field name="title"/>
    <field name="x121Address"/>
    <field name="registeredAddress"/>
    <field name="destinationIndicator"/>
    <field name="preferredDeliveryMethod"/>
    <field name="telexNumber"/>
    <field name="teletexTerminalIdentifier"/>
    <field name="internationaliSDNNumber"/>
    <field name="facsimileTelephoneNumber"/>
    <field name="street"/>
    <field name="postOfficeBox"/>
    <field name="postalCode"/>
    <field name="postalAddress"/>
    <field name="physicalDeliveryOfficeName"/>
    <field name="ou"/>
    <field name="st"/>
    <field name="l"/>

    <!-- inetOrgPerson -->
    <field name="audio"/>
    <field name="businessCategory"/>
    <field name="carLicense"/>
    <field name="departmentNumber"/>
    <field name="displayName"/>
    <field name="employeeNumber"/>
    <field name="employeeType"/>
    <field name="givenName"/>
    <field name="homePhone"/>
    <field name="homePostalAddress"/>
    <field name="initials"/>
    <field name="jpegPhoto"/>
    <field name="labeledURI"/>
    <field name="mail"/>
    <field name="manager"/>
    <field name="mobile"/>
    <field name="o"/>
    <field name="pager"/>
    <field name="photo"/>
    <field name="roomNumber"/>
    <field name="secretary"/>
    <field name="uid"/>
    <field name="userCertificate"/>
    <field name="x500uniqueIdentifier"/>
    <field name="preferredLanguage"/>
    <field name="userSMIMECertificate"/>
    <field name="userPKCS12"/>

    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>person,organizationalPerson,inetOrgPerson</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=inetOrgPerson)</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Users,${ldap.suffix}</param-value>
    </parameter>

  </source>

  <source name="groups">

    <connection-name>LDAP</connection-name>

    <field name="dn" primaryKey="true"/>
    <field name="cn"/>
    <field name="uniqueMember"/>
    <field name="businessCategory"/>
    <field name="owner"/>
    <field name="ou"/>
    <field name="o"/>
    <field name="description"/>

    <parameter>
      <param-name>objectClasses</param-name>
      <param-value>groupOfUniqueNames</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=groupOfUniqueNames)</param-value>
    </parameter>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>ou=Groups,${ldap.suffix}</param-value>
    </parameter>
    
  </source>

</sources>

=== edewata/penrose-server/samples/ipa_samba/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="ipa">
    <connection-name>IPA</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>dc=example,dc=com</param-value>
    </parameter>
  </source>

  <source name="ipa_users">
    <connection-name>IPA</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>cn=users,cn=accounts,dc=example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
  </source>

  <source name="ipa_groups">
    <connection-name>IPA</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>cn=groups,cn=accounts,dc=example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
  </source>

  <source name="ipa_hosts">
    <connection-name>IPA</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>cn=hosts,cn=accounts,dc=example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
  </source>

  <source name="ipa_changelog">
    <connection-name>IPA</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>cn=changelog</param-value>
    </parameter>
  </source>

  <source name="ipa_tracker">
    <connection-name>Database</connection-name>
    <field name="changeNumber" type="INTEGER" primaryKey="true"/>
    <field name="changeTimestamp" type="DATETIME"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>ipa_tracker</param-value>
    </parameter>
    <parameter>
      <param-name>create</param-name>
      <param-value>true</param-value>
    </parameter>
  </source>

  <source name="sambaFE">
    <connection-name>SambaFE</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>DC=samba,DC=example,DC=com</param-value>
    </parameter>
  </source>

  <source name="sambaUsersFE">
    <connection-name>SambaFE</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>DC=samba,DC=example,DC=com</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(&amp;(objectClass=user)(!(objectClass=computer))(!(servicePrincipalName=*)))</param-value>
    </parameter>
    <parameter>
      <param-name>attributes</param-name>
      <param-value>
          objectClass cn sn sAMAccountName
          homeDirectory accountExpires pwdLastSet
          objectSid lastLogon scriptPath
          profilePath logonCount badPwdCount primaryGroupID
          userAccountControl objectGUID supplementalCredentials
      </param-value>
    </parameter>
  </source>

  <source name="sambaUsersBE">
    <connection-name>SambaBE</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>DC=samba,DC=example,DC=com</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(&amp;(objectClass=user)(!(objectClass=computer))(!(servicePrincipalName=*)))</param-value>
    </parameter>
    <parameter>
      <param-name>attributes</param-name>
      <param-value>
          objectClass cn sn sAMAccountName
          sambaHomePath accountExpires sambaPwdLastSet
          sambaSID lastLogon scriptPath
          sambaProfilePath logonCount badPwdCount primaryGroupID
          userAccountControl nsUniqueId supplementalCredentials
      </param-value>
    </parameter>
  </source>

  <source name="samba_groups">
    <connection-name>SambaBE</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>DC=samba,DC=example,DC=com</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=group)</param-value>
    </parameter>
  </source>

  <source name="samba_hosts">
    <connection-name>SambaBE</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>DC=samba,DC=example,DC=com</param-value>
    </parameter>
    <parameter>
      <param-name>filter</param-name>
      <param-value>(objectClass=computer)</param-value>
    </parameter>
  </source>

</sources>

=== edewata/penrose-server/samples/acl/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="users">
    <connection-name>Database</connection-name>
    <field name="username" primaryKey="true"/>
    <field name="firstName"/>
    <field name="lastName"/>
    <field name="password"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>users</param-value>
    </parameter>
  </source>

</sources>

=== edewata/penrose-server/samples/samba_ipa/DIR-INF/sources-ipa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="ipa">
    <connection-name>IPA</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>dc=example,dc=com</param-value>
    </parameter>
  </source>

  <source name="ipaUsers">
    <connection-name>IPA</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>cn=users,cn=accounts,dc=example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
  </source>

  <source name="ipa_groups">
    <connection-name>IPA</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>cn=groups,cn=accounts,dc=example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
  </source>

  <source name="ipa_hosts">
    <connection-name>IPA</connection-name>
    <parameter>
      <param-name>baseDn</param-name>
      <param-value>cn=hosts,cn=accounts,dc=example,dc=com</param-value>
    </parameter>
    <parameter>
      <param-name>scope</param-name>
      <param-value>ONELEVEL</param-value>
    </parameter>
  </source>

</sources>

=== edewata/penrose-server/samples/posix/DIR-INF/sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sources PUBLIC
  "-//Penrose/DTD Sources ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/sources.dtd">

<sources>

  <source name="posixAccount">
    <connection-name>Posix</connection-name>
    <field name="cn"/>
    <field name="uid" primaryKey="true"/>
    <field name="uidNumber" type="INTEGER"/>
    <field name="gidNumber" type="INTEGER"/>
    <field name="homeDirectory"/>
    <field name="authPassword"/>
    <field name="userPassword"/>
    <field name="loginShell"/>
    <field name="gecos"/>
    <field name="description"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>posixAccount</param-value>
    </parameter>
  </source>

  <source name="shadowAccount">
    <connection-name>Posix</connection-name>
    <field name="uid" primaryKey="true"/>
    <field name="authPassword"/>
    <field name="userPassword"/>
    <field name="description"/>
    <field name="shadowLastChange" type="INTEGER"/>
    <field name="shadowMin" type="INTEGER"/>
    <field name="shadowMax" type="INTEGER"/>
    <field name="shadowWarning" type="INTEGER"/>
    <field name="shadowInactive" type="INTEGER"/>
    <field name="shadowExpire" type="INTEGER"/>
    <field name="shadowFlag" type="INTEGER"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>shadowAccount</param-value>
    </parameter>
  </source>

  <source name="posixGroup">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="gidNumber" type="INTEGER"/>
    <field name="authPassword"/>
    <field name="userPassword"/>
    <field name="description"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>posixGroup</param-value>
    </parameter>
  </source>

  <source name="posixGroup_memberUid">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="memberUid" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>posixGroup_memberUid</param-value>
    </parameter>
  </source>

  <source name="device">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="serialNumber"/>
    <field name="seeAlso"/>
    <field name="owner"/>
    <field name="ou"/>
    <field name="o"/>
    <field name="l"/>
    <field name="description"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>device</param-value>
    </parameter>
  </source>

  <source name="ipHost">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="ipHostNumber"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>ipHost</param-value>
    </parameter>
  </source>

  <source name="ipHost_alias">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="alias" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>ipHost_alias</param-value>
    </parameter>
  </source>

  <source name="ieee802Device">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="macAddress"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>ieee802Device</param-value>
    </parameter>
  </source>

  <source name="ipNetwork">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="ipNetworkNumber"/>
    <field name="ipNetmaskNumber"/>
    <field name="l"/>
    <field name="description"/>
    <field name="manager"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>ipNetwork</param-value>
    </parameter>
  </source>

  <source name="ipNetwork_alias">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="alias" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>ipNetwork_alias</param-value>
    </parameter>
  </source>

  <source name="ipService">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="ipServicePort" type="INTEGER"/>
    <field name="ipServiceProtocol" primaryKey="true"/>
    <field name="description"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>ipService</param-value>
    </parameter>
  </source>

  <source name="ipService_alias">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="ipServiceProtocol" primaryKey="true"/>
    <field name="alias" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>ipService_alias</param-value>
    </parameter>
  </source>

  <source name="ipProtocol">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="ipProtocolNumber"/>
    <field name="description"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>ipProtocol</param-value>
    </parameter>
  </source>

  <source name="ipProtocol_alias">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="alias" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>ipProtocol_alias</param-value>
    </parameter>
  </source>

  <source name="oncRpc">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="oncRpcNumber"/>
    <field name="description"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>oncRpc</param-value>
    </parameter>
  </source>

  <source name="oncRpc_alias">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="alias" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>oncRpc_alias</param-value>
    </parameter>
  </source>

  <source name="nisNetgroup">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="description"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>nisNetgroup</param-value>
    </parameter>
  </source>

  <source name="nisNetgroup_nisNetgroupTriple">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="nisNetgroupTriple" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>nisNetgroup_nisNetgroupTriple</param-value>
    </parameter>
  </source>

  <source name="nisNetgroup_memberNisNetgroup">
    <connection-name>Posix</connection-name>
    <field name="cn" primaryKey="true"/>
    <field name="memberNisNetgroup" primaryKey="true"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>nisNetgroup_memberNisNetgroup</param-value>
    </parameter>
  </source>

  <source name="automountMap">
    <connection-name>Posix</connection-name>
    <field name="automountMapName" primaryKey="true"/>
    <field name="description"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>automountMap</param-value>
    </parameter>
  </source>

  <source name="automount">
    <connection-name>Posix</connection-name>
    <field name="automountMapName" primaryKey="true"/>
    <field name="automountKey" primaryKey="true"/>
    <field name="automountInformation"/>
    <field name="description"/>
    <parameter>
      <param-name>table</param-name>
      <param-value>automount</param-value>
    </parameter>
  </source>

</sources>
