=== edewata/penrose-server/common/src/java/org/safehaus/penrose/scheduler/scheduler.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT scheduler (description?, scheduler-class, parameter*, job*, trigger*)>
<!ATTLIST scheduler enabled CDATA #IMPLIED>
<!ELEMENT scheduler-class (#PCDATA)>

<!ELEMENT job (description?, job-class, parameter*)>
<!ATTLIST job enabled CDATA #IMPLIED>
<!ATTLIST job name CDATA #IMPLIED>
<!ELEMENT job-class (#PCDATA)>

<!ELEMENT trigger (description?, trigger-class, job-name, parameter*)>
<!ATTLIST trigger enabled CDATA #IMPLIED>
<!ATTLIST trigger name CDATA #IMPLIED>
<!ELEMENT trigger-class (#PCDATA)>
<!ELEMENT job-name (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== edewata/penrose-server/samples/lockout/DIR-INF/scheduler.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scheduler PUBLIC
  "-//Penrose/DTD Scheduler ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/scheduler.dtd">

<scheduler enabled="true">

  <scheduler-class>org.safehaus.penrose.scheduler.quartz.QuartzScheduler</scheduler-class>

  <job name="LockoutJob">
    <job-class>org.safehaus.penrose.lockout.LockoutJob</job-class>
  </job>

  <trigger>
    <trigger-class>org.safehaus.penrose.scheduler.quartz.CronTrigger</trigger-class>
    <job-name>LockoutJob</job-name>
    <parameter>
      <param-name>expression</param-name>
      <param-value>0 * * * * ?</param-value>
    </parameter>
  </trigger>

</scheduler>

=== edewata/penrose-server/samples/scheduler/DIR-INF/scheduler.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scheduler PUBLIC
  "-//Penrose/DTD Scheduler ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/scheduler.dtd">

<scheduler>

  <scheduler-class>org.safehaus.penrose.scheduler.quartz.QuartzScheduler</scheduler-class>

  <job name="DemoJob">
    <job-class>org.safehaus.penrose.example.scheduler.DemoJob</job-class>
  </job>

  <trigger>
    <trigger-class>org.safehaus.penrose.scheduler.quartz.CronTrigger</trigger-class>
    <job-name>DemoJob</job-name>
    <parameter>
      <param-name>expression</param-name>
      <param-value>0 * * * * ?</param-value>
    </parameter>
  </trigger>

</scheduler>
